/**
 * Single source of truth for every user-facing string in the SPA.
 * Product rule: all user-visible copy must be English. Do not inline strings
 * in feature code; extend this file instead.
 */
export const copy = {
  app: {
    name: 'WeBox',
    tagline: 'Enterprise employee meal ordering',
  },
  nav: {
    menu: 'Menu',
    cart: 'Cart',
    orders: 'My Orders',
    settings: 'Settings',
    console: 'Console',
    consoleDishes: 'Dish Management',
    consoleDailyMenu: 'Daily Menu',
    logout: 'Log out',
    openNavigation: 'Open navigation',
  },
  common: {
    loading: 'Loading…',
    save: 'Save',
    saved: 'Saved.',
    cancel: 'Cancel',
    confirm: 'Confirm',
    submit: 'Submit',
    edit: 'Edit',
    remove: 'Remove',
    close: 'Close',
    back: 'Back',
    search: 'Search',
    retry: 'Retry',
    add: 'Add',
    create: 'Create',
    actions: 'Actions',
    total: 'Total',
    quantity: 'Quantity',
    price: 'Price',
    status: 'Status',
    date: 'Date',
    name: 'Name',
    description: 'Description',
    optional: 'Optional',
    required: 'Required',
    yes: 'Yes',
    no: 'No',
  },
  errors: {
    network:
      'Cannot reach the server. Make sure the backend is running and check your connection, then try again.',
    unauthorized: 'Your session has expired. Please log in again.',
    forbidden: 'You do not have permission to access this page.',
    notFound: 'The page or resource you requested was not found.',
    server: 'Something went wrong on our side. Please try again in a moment.',
    validation: 'Please review the highlighted fields and try again.',
    generic: 'Something went wrong. Please try again.',
    loadFailedTitle: 'Unable to load data',
    loadFailedBody:
      'We could not load this content. If the backend service is still starting up, wait a moment and retry.',
  },
  empty: {
    menu: 'No dishes match your filters for this day.',
    cart: 'Your cart is empty. Browse the menu and add something tasty.',
    orders: 'You have not placed any orders yet.',
    addresses: 'No saved addresses yet.',
    dailyMenu: 'No dishes are scheduled for this date yet.',
  },
  auth: {
    loginTitle: 'Log in to WeBox',
    registerTitle: 'Create your account',
    email: 'Work email',
    emailPlaceholder: 'you@company.com',
    emailRequired: 'Please enter your email.',
    emailInvalid: 'Please enter a valid email address.',
    emailTooLong: 'Email must be 200 characters or fewer.',
    password: 'Password',
    passwordPlaceholder: 'At least 8 characters with letters and numbers',
    passwordRequired: 'Please enter your password.',
    passwordRule: 'Password must be at least 8 characters and contain both letters and numbers.',
    loginSubmit: 'Log in',
    registerSubmit: 'Sign up',
    loginFailed: 'Incorrect email or password.',
    registerFailed: 'Could not create the account. The email may already be registered.',
    toRegister: 'New here? Create an account',
    toLogin: 'Already have an account? Log in',
    registerSuccess: 'Account created. You are now logged in.',
    logoutSuccess: 'You have been logged out.',
  },
  guard: {
    forbiddenTitle: '403 - No access',
    forbiddenBody: 'This area is restricted to administrators.',
    backToMenu: 'Back to menu',
    notFoundTitle: '404 - Page not found',
  },
  menu: {
    title: "Today's Menu",
    searchPlaceholder: 'Search dishes by name or description',
    categoriesPlaceholder: 'Filter by categories',
    recommendedToggle: 'Recommended for me',
    recommendedTag: 'Recommended',
    allergenTag: 'Contains allergens you track',
    soldOut: 'Sold out',
    portionsLeft: 'portions left',
    details: 'Details',
    addToCart: 'Add to cart',
    addedToCart: 'Added to cart.',
    spiceLevel: 'Spice level',
    protein: 'Protein',
    allergens: 'Allergens',
    customize: 'Customize your dish',
    selectRequired: 'Please complete all required options.',
    optionGroupRequired: 'Required',
    optionGroupPickOne: 'Choose 1',
    optionGroupPickUpTo: 'Choose up to',
    imageComingSoon: 'Image coming soon',
  },
  allergenConfirm: {
    title: 'Allergen notice',
    body: 'This dish contains allergens listed in your preferences:',
    confirm: 'Add anyway',
    cancel: 'Do not add',
  },
  cart: {
    title: 'Your Cart',
    portionLimitReached: 'You can order up to 5 portions per meal.',
    portionLimitHint: 'Maximum 5 portions per order.',
    subtotal: 'Subtotal',
    checkout: 'Go to checkout',
    keepBrowsing: 'Keep browsing',
    removeLine: 'Remove this item',
    optionsLabel: 'Options',
  },
  checkout: {
    title: 'Checkout',
    deliveryDate: 'Delivery date',
    mealPeriod: 'Meal period',
    cutoffPassed: 'Ordering for this slot has closed.',
    address: 'Delivery address',
    newAddress: 'Use a new address',
    newAddressPlaceholder: 'Building, floor, and delivery notes (max 200 characters)',
    addressRequired: 'Please choose or enter a delivery address.',
    addressTooLong: 'Address must be 200 characters or fewer.',
    defaultBadge: 'Default',
    orderSummary: 'Order summary',
    budgetNotice: 'This order exceeds your per-meal budget of {budget}. You can still place it.',
    placeOrder: 'Place order',
    placing: 'Placing order…',
    successTitle: 'Order placed!',
    successOrderNumber: 'Order number',
    successDelivery: 'Delivery',
    viewOrders: 'View my orders',
    backToMenu: 'Back to menu',
    duplicateTitle: 'You already have an active order for this slot.',
    duplicateBody: 'Only one active order per meal period is allowed. You can view or cancel it from My Orders.',
    stockTitle: 'Some dishes are no longer available in the requested quantity:',
    stockOnlyLeft: 'only {count} left',
    stockSoldOut: 'sold out',
    emptyNotice: 'Your cart is empty. Add dishes from the menu before checking out.',
  },
  orders: {
    title: 'My Orders',
    orderNumber: 'Order',
    detailTitle: 'Order details',
    deliveryOn: 'Delivery',
    cancelOrder: 'Cancel order',
    cancelConfirmTitle: 'Cancel this order?',
    cancelConfirmBody: 'Reserved stock will be released. This cannot be undone.',
    cancelSuccess: 'Order cancelled.',
    cancelFailed: 'This order can no longer be cancelled.',
    items: 'Items',
    addressLabel: 'Delivery address',
    placedAt: 'Placed at',
    unitPrice: 'Unit price',
  },
  orderStatus: {
    PENDING: 'Pending',
    CONFIRMED: 'Confirmed',
    CANCELLED: 'Cancelled',
    COMPLETED: 'Completed',
  },
  mealPeriod: {
    LUNCH: 'Lunch',
    DINNER: 'Dinner',
  },
  spice: {
    NONE: 'No spice',
    MILD: 'Mild',
    MEDIUM: 'Medium',
    HOT: 'Hot',
  },
  settings: {
    title: 'Preferences',
    dietaryTitle: 'Dietary preferences',
    allergens: 'Allergens to watch',
    categories: 'Favorite cuisines',
    spice: 'Spice preference',
    taste: 'Taste intensity',
    budget: 'Per-meal budget (CNY)',
    budgetPlaceholder: 'e.g. 35',
    budgetInvalid: 'Budget must be a positive amount.',
    recommended: 'Recommended for me',
    recommendedHint:
      'When enabled, dishes matching your cuisines and spice preference are ranked first and highlighted.',
    saveSuccess: 'Preferences saved.',
    tasteOptions: {
      LIGHT: 'Light',
      REGULAR: 'Regular',
      RICH: 'Rich',
    },
  },
  console: {
    dishesTitle: 'Dish Management',
    newDish: 'New dish',
    editDish: 'Edit dish',
    searchPlaceholder: 'Search by dish name',
    categoryFilter: 'All categories',
    listed: 'Listed',
    unlisted: 'Unlisted',
    listAction: 'List',
    unlistAction: 'Unlist',
    listConfirm: 'List this dish so employees can see it?',
    unlistConfirm: 'Unlist this dish? It will disappear from the menu.',
    statusUpdated: 'Dish status updated.',
    dishSaved: 'Dish saved.',
    dishSaveFailed: 'Could not save the dish. Please review the form.',
    imageUpload: 'Upload image',
    imageUploadHint: 'Save the dish first, then upload an image.',
    imageUploadSuccess: 'Image uploaded.',
    imageUploadFailed: 'Image upload failed. Please try another file.',
    priceYuan: 'Price (CNY)',
    priceRequired: 'Please enter a price.',
    priceInvalid: 'Price must be greater than zero.',
    nameRequired: 'Please enter the dish name.',
    categoriesLabel: 'Categories',
    proteinLabel: 'Protein source',
    spiceLabel: 'Spice level',
    allergensLabel: 'Allergens',
    optionGroupsLabel: 'Customization options',
    addOptionGroup: 'Add option group',
    addOptionItem: 'Add option',
    groupNamePlaceholder: 'Group name, e.g. Size',
    itemNamePlaceholder: 'Option name, e.g. Large',
    itemExtraPricePlaceholder: 'Extra price (CNY)',
    groupRequired: 'Required group',
    pickOne: 'Single choice',
    pickMany: 'Multiple choice',
    dailyMenuTitle: 'Daily Menu',
    dailyMenuHint: 'Configure which dishes are offered on a date and how many portions are available.',
    pickDate: 'Menu date',
    addDish: 'Add dish to menu',
    availableQuantity: 'Available quantity',
    quantityInvalid: 'Quantity must be a non-negative integer.',
    menuSaved: 'Daily menu saved.',
    removeFromMenu: 'Remove from this day',
    noImage: 'No image',
  },
} as const;

export type Copy = typeof copy;
