package com.webbox.menu;

import com.webbox.common.ApiException;
import java.time.*;
import java.util.*;
import java.util.stream.Collectors;
import org.springframework.cache.annotation.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;
import static com.webbox.menu.MenuModels.*;

@Service @CacheConfig(cacheNames="visibleMenu")
public class MenuService {
 private final JdbcTemplate jdbc; private final Clock clock;
 public MenuService(JdbcTemplate jdbc,Clock clock){this.jdbc=jdbc;this.clock=clock;}
 public LocalDate defaultMenuDate(){ LocalDateTime now=LocalDateTime.now(clock); return now.toLocalTime().isBefore(LocalTime.of(15,0)) ? now.toLocalDate() : now.toLocalDate().plusDays(1); }
 public MenuPage list(LocalDate requested,String q,List<String> categories,int page,int size) { LocalDate date=requested==null?defaultMenuDate():requested; if(q!=null&&q.length()>50) throw new ApiException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","Search must be 50 characters or fewer."); List<Dish> all=visible(date); String search=q==null?"":q.trim().toLowerCase(Locale.ROOT); Set<String> cs=categories==null?Set.of():new HashSet<>(categories); List<Dish> filtered=all.stream().filter(d->search.isEmpty()||d.name().toLowerCase().contains(search)||d.description().toLowerCase().contains(search)).filter(d->cs.isEmpty()||cs.contains(d.category())).toList(); int from=Math.min(page*size,filtered.size()); int to=Math.min(from+size,filtered.size()); return new MenuPage(filtered.subList(from,to),filtered.size(),page,size,date.toString()); }
 @Cacheable(key="#date.toString()") public List<Dish> visible(LocalDate date) { return rows(date,true); }
 public Dish detail(long id,LocalDate date){ return rows(date==null?defaultMenuDate():date,true).stream().filter(d->d.id()==id).findFirst().orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"DISH_NOT_FOUND","Dish not found in this menu.")); }
 public List<Dish> adminList(String q,String category){ return rows(null,false).stream().filter(d->q==null||q.isBlank()||d.name().toLowerCase().contains(q.toLowerCase())).filter(d->category==null||category.isBlank()||category.equals(d.category())).toList(); }
 public Dish adminDish(long id){ return rows(null,false).stream().filter(d->d.id()==id).findFirst().orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"DISH_NOT_FOUND","Dish not found.")); }
 private List<Dish> rows(LocalDate date,boolean menuOnly) { String sql=menuOnly?"select d.*,dm.available_quantity from dishes d join daily_menus dm on dm.dish_id=d.id where dm.menu_date=? and d.visible=true order by d.id":"select d.*,null as available_quantity from dishes d order by d.id"; Object[] args=menuOnly?new Object[]{date}:new Object[]{}; return jdbc.query(sql,(rs,n)->dish(rs.getLong("id"),rs.getString("name"),rs.getString("description"),rs.getString("category"),rs.getString("protein"),rs.getString("spice_level"),rs.getLong("price_cents"),rs.getString("image_url"),rs.getBoolean("visible"),rs.getObject("available_quantity",Integer.class)),args); }
 private Dish dish(long id,String name,String desc,String category,String protein,String spice,long price,String image,boolean visible,Integer quantity){ List<String> allergens=jdbc.query("select allergen from dish_allergens where dish_id=?",(rs,n)->rs.getString(1),id); List<OptionGroup> groups=jdbc.query("select id,name,required_group,min_selections,max_selections from option_groups where dish_id=?",(rs,n)->{long gid=rs.getLong(1); return new OptionGroup(gid,rs.getString(2),rs.getBoolean(3),rs.getInt(4),rs.getInt(5),jdbc.query("select id,name,extra_price_cents from option_items where option_group_id=?",(a,b)->new OptionItem(a.getLong(1),a.getString(2),a.getLong(3)),gid));},id); return new Dish(id,name,desc,category,protein,spice,price,image,visible,allergens,groups,quantity); }
 @CacheEvict(allEntries=true) public void clearVisibleCache() {}
 @CacheEvict(allEntries=true) public Dish create(DishInput in){ validate(in); jdbc.update("insert into dishes(name,description,category,protein,spice_level,price_cents,image_url,visible) values(?,?,?,?,?,?,?,?)",in.name(),in.description(),in.category(),in.protein(),in.spiceLevel(),in.priceCents(),in.imageUrl(),in.visible()==null||in.visible()); long id=jdbc.queryForObject("select last_insert_id()",Long.class); replaceDetails(id,in); return adminDish(id); }
 @CacheEvict(allEntries=true) public Dish update(long id,DishInput in){ adminDish(id); validate(in); jdbc.update("update dishes set name=?,description=?,category=?,protein=?,spice_level=?,price_cents=?,image_url=?,visible=? where id=?",in.name(),in.description(),in.category(),in.protein(),in.spiceLevel(),in.priceCents(),in.imageUrl(),in.visible()==null||in.visible(),id); jdbc.update("delete from dish_allergens where dish_id=?",id); jdbc.update("delete from option_groups where dish_id=?",id); replaceDetails(id,in); return adminDish(id); }
 @CacheEvict(allEntries=true) public Dish setVisibility(long id,boolean visible){ jdbc.update("update dishes set visible=? where id=?",visible,id); return adminDish(id); }
 @CacheEvict(allEntries=true) public Dish storeImage(long id, MultipartFile file){ adminDish(id); try { jdbc.update("insert into dish_images(dish_id,file_name,content_type,image_data) values(?,?,?,?) on duplicate key update file_name=values(file_name),content_type=values(content_type),image_data=values(image_data)",id,file.getOriginalFilename(),file.getContentType(),file.getBytes()); jdbc.update("update dishes set image_url=? where id=?","/api/menu/"+id+"/image",id); return adminDish(id); } catch(java.io.IOException e) { throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_IMAGE","The image could not be read."); } }
 public ImageData image(long id){ return jdbc.query("select content_type,image_data from dish_images where dish_id=?",rs->rs.next()?new ImageData(rs.getString(1),rs.getBytes(2)):null,id); }
 public record ImageData(String contentType,byte[] bytes) {}
 private void validate(DishInput in){ if(in==null||blank(in.name())||blank(in.description())||blank(in.category())||in.priceCents()==null||in.priceCents()<0) throw new ApiException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","Dish name, description, category and a non-negative price are required."); }
 private boolean blank(String v){return v==null||v.isBlank();}
 private void replaceDetails(long id,DishInput in){ for(String a: Optional.ofNullable(in.allergens()).orElse(List.of())) jdbc.update("insert into dish_allergens(dish_id,allergen) values(?,?)",id,a); for(OptionGroupInput g:Optional.ofNullable(in.optionGroups()).orElse(List.of())) { jdbc.update("insert into option_groups(dish_id,name,required_group,min_selections,max_selections) values(?,?,?,?,?)",id,g.name(),Boolean.TRUE.equals(g.required()),g.minSelections()==null?0:g.minSelections(),g.maxSelections()==null?1:g.maxSelections()); long gid=jdbc.queryForObject("select last_insert_id()",Long.class); for(OptionItemInput i:Optional.ofNullable(g.items()).orElse(List.of())) jdbc.update("insert into option_items(option_group_id,name,extra_price_cents) values(?,?,?)",gid,i.name(),i.extraPriceCents()==null?0:i.extraPriceCents()); } }
 @CacheEvict(allEntries=true) public void configureDaily(DailyMenuInput in){ LocalDate date; try{date=LocalDate.parse(in.menuDate());}catch(Exception e){throw new ApiException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","menuDate must use YYYY-MM-DD format.");} for(DailyMenuDishInput d:in.dishes()){if(d.availableQuantity()<0)throw new ApiException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","Available quantity cannot be negative."); if(jdbc.queryForObject("select count(*) from dishes where id=?",Integer.class,d.dishId())==0)throw new ApiException(HttpStatus.NOT_FOUND,"DISH_NOT_FOUND","Dish not found."); jdbc.update("insert into daily_menus(menu_date,dish_id,available_quantity) values(?,?,?) on duplicate key update available_quantity=values(available_quantity)",date,d.dishId(),d.availableQuantity());} }
}
