CREATE TABLE dish_images (
  dish_id BIGINT PRIMARY KEY,
  file_name VARCHAR(255) NOT NULL,
  content_type VARCHAR(100) NOT NULL,
  image_data LONGBLOB NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_dish_image FOREIGN KEY(dish_id) REFERENCES dishes(id) ON DELETE CASCADE
);
