package com.webbox.order;

import com.webbox.common.ApiException;
import java.time.LocalDate;
import java.util.*;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import static com.webbox.order.OrderModels.*;

@Service
public class OrderService {
 private final JdbcTemplate jdbc; private final CutoffPolicy cutoff; private final PricingService pricing; private final InventoryService inventory;
 public OrderService(JdbcTemplate jdbc,CutoffPolicy cutoff,PricingService pricing,InventoryService inventory){this.jdbc=jdbc;this.cutoff=cutoff;this.pricing=pricing;this.inventory=inventory;}
 public OrderSuggestion suggestion(){return cutoff.suggestion();}
 @Transactional public OrderView create(long userId,String key,OrderRequest r){
  if(key==null||key.isBlank()||key.length()>255)throw new ApiException(HttpStatus.BAD_REQUEST,"MISSING_IDEMPOTENCY_KEY","Idempotency-Key is required and must be 255 characters or fewer.");
  Long existing=reserveIdempotencyKey(userId,key); if(existing!=null)return detail(userId,existing);
  if(r.items()==null||r.items().isEmpty())throw new ApiException(HttpStatus.BAD_REQUEST,"EMPTY_ORDER","Order must contain at least one item."); int portions=r.items().stream().mapToInt(OrderLineRequest::quantity).sum();if(portions>5)throw new ApiException(HttpStatus.BAD_REQUEST,"PORTION_LIMIT","An order cannot contain more than 5 portions.");
  OrderSuggestion fallback=cutoff.suggestion(); LocalDate requestedDate=parseDate(r.deliveryDate(),fallback.deliveryDate()); String requestedMeal=r.mealPeriod()==null||r.mealPeriod().isBlank()?fallback.mealPeriod():r.mealPeriod().toUpperCase(Locale.ROOT);if(!Set.of("LUNCH","DINNER").contains(requestedMeal))throw new ApiException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","mealPeriod must be LUNCH or DINNER."); OrderSuggestion resolved=cutoff.resolve(requestedDate,requestedMeal); LocalDate date=LocalDate.parse(resolved.deliveryDate()); String meal=resolved.mealPeriod();
  String address=address(userId,r); List<Calculated> calculated=new ArrayList<>(); for(OrderLineRequest l:r.items())calculated.add(calculate(date,l));
  if(jdbc.queryForObject("select count(*) from orders where user_id=? and active_meal_key=?",Integer.class,userId,date+"#"+meal)>0)throw new ApiException(HttpStatus.CONFLICT,"ACTIVE_ORDER_EXISTS","You already have an active order for this meal period.");
  Map<Long,Integer> grouped=new TreeMap<>();for(Calculated c:calculated)grouped.merge(c.dishId,c.quantity,Integer::sum); inventory.reserve(date,grouped,this::dishName);
  long total=calculated.stream().mapToLong(Calculated::subtotal).sum(); jdbc.update("insert into orders(user_id,delivery_date,meal_period,status,active_meal_key,address_snapshot,total_cents,idempotency_key) values(?,?,?,?,?,?,?,?)",userId,date,meal,"PENDING",date+"#"+meal,address,total,key); long orderId=jdbc.queryForObject("select last_insert_id()",Long.class);
  for(Calculated c:calculated){jdbc.update("insert into order_items(order_id,dish_id,dish_name,unit_price_cents,quantity,subtotal_cents) values(?,?,?,?,?,?)",orderId,c.dishId,c.name,c.unit,c.quantity,c.subtotal);long itemId=jdbc.queryForObject("select last_insert_id()",Long.class);for(OrderOption o:c.options)jdbc.update("insert into order_item_options(order_item_id,option_item_id,option_name,extra_price_cents) values(?,?,?,?)",itemId,o.optionItemId(),o.name(),o.extraPriceCents());}
  jdbc.update("update idempotency_records set order_id=?,request_hash=?,response_status=? where user_id=? and idempotency_key=?",orderId,"server-validated",201,userId,key);return detail(userId,orderId);
 }
 public List<OrderView> list(long uid){return jdbc.query("select id from orders where user_id=? order by created_at desc",(rs,n)->rs.getLong(1),uid).stream().map(id->detail(uid,id)).toList();}
 public OrderView detail(long uid,long id){var heads=jdbc.query("select id,delivery_date,meal_period,status,address_snapshot,total_cents from orders where id=? and user_id=?",(rs,n)->new Object[]{rs.getLong(1),rs.getDate(2).toLocalDate(),rs.getString(3),rs.getString(4),rs.getString(5),rs.getLong(6)},id,uid);if(heads.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"ORDER_NOT_FOUND","Order not found.");Object[] h=heads.get(0);List<OrderItem> items=jdbc.query("select id,dish_id,dish_name,unit_price_cents,quantity,subtotal_cents from order_items where order_id=?",(rs,n)->{long itemId=rs.getLong(1);return new OrderItem(rs.getLong(2),rs.getString(3),rs.getLong(4),rs.getInt(5),rs.getLong(6),jdbc.query("select option_item_id,option_name,extra_price_cents from order_item_options where order_item_id=?",(a,b)->new OrderOption(a.getLong(1),a.getString(2),a.getLong(3)),itemId));},id);long orderId=(Long)h[0];return new OrderView(orderId,String.format("WB-%08d",orderId),h[1].toString(),(String)h[2],displayStatus((String)h[3]),(String)h[4],(Long)h[5],items);}
 @Transactional public OrderView cancel(long uid,long id){var h=jdbc.query("select delivery_date,meal_period,status from orders where id=? and user_id=?",(rs,n)->new Object[]{rs.getDate(1).toLocalDate(),rs.getString(2),rs.getString(3)},id,uid);if(h.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"ORDER_NOT_FOUND","Order not found.");Object[] head=h.get(0);if(!inventory.markCancelled(uid,id))throw new ApiException(HttpStatus.CONFLICT,"ORDER_NOT_CANCELLABLE","Only a pending order can be cancelled."); for(Object[] i:jdbc.query("select dish_id,quantity from order_items where order_id=?",(rs,n)->new Object[]{rs.getLong(1),rs.getInt(2)},id))inventory.restore((LocalDate)head[0],(Long)i[0],(Integer)i[1]);return detail(uid,id);}
 private Calculated calculate(LocalDate date,OrderLineRequest line){var d=jdbc.query("select d.id,d.name,d.price_cents from dishes d join daily_menus m on m.dish_id=d.id where d.id=? and m.menu_date=? and d.visible=true",(rs,n)->new Object[]{rs.getLong(1),rs.getString(2),rs.getLong(3)},line.dishId(),date);if(d.isEmpty())throw new ApiException(HttpStatus.BAD_REQUEST,"DISH_UNAVAILABLE","A selected dish is not available for this menu.");Object[] dish=d.get(0);List<Long> ids=line.optionItemIds()==null?List.of():line.optionItemIds();if(new HashSet<>(ids).size()!=ids.size())throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_OPTIONS","Each option can only be selected once.");List<Object[]> selected=new ArrayList<>();for(Long oid:ids){var x=jdbc.query("select oi.id,oi.name,oi.extra_price_cents,og.id from option_items oi join option_groups og on oi.option_group_id=og.id where oi.id=? and og.dish_id=?",(rs,n)->new Object[]{rs.getLong(1),rs.getString(2),rs.getLong(3),rs.getLong(4)},oid,line.dishId());if(x.isEmpty())throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_OPTIONS","An option does not belong to the selected dish.");selected.add(x.get(0));}for(Object[] group:jdbc.query("select id,required_group,min_selections,max_selections from option_groups where dish_id=?",(rs,n)->new Object[]{rs.getLong(1),rs.getBoolean(2),rs.getInt(3),rs.getInt(4)},line.dishId())){long gid=(Long)group[0];long count=selected.stream().filter(o->((Long)o[3])==gid).count();if((Boolean)group[1]&&count<(Integer)group[2]||count>(Integer)group[3])throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_OPTIONS","Required customization options are missing or invalid.");}List<OrderOption> opts=selected.stream().map(x->new OrderOption((Long)x[0],(String)x[1],(Long)x[2])).toList();long unit=(Long)dish[2]+opts.stream().mapToLong(OrderOption::extraPriceCents).sum();return new Calculated((Long)dish[0],(String)dish[1],unit,line.quantity(),pricing.price((Long)dish[2],line.quantity(),opts.stream().map(OrderOption::extraPriceCents).toList()),opts);}
 private String address(long userId,OrderRequest r){if(r.addressId()!=null){String a=jdbc.query("select address from addresses where id=? and user_id=?",rs->rs.next()?rs.getString(1):null,r.addressId(),userId);if(a==null)throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_ADDRESS","The selected address does not belong to you.");return a;}if(r.deliveryAddress()!=null&&!r.deliveryAddress().isBlank())return r.deliveryAddress();throw new ApiException(HttpStatus.BAD_REQUEST,"ADDRESS_REQUIRED","A delivery address is required.");}
 private LocalDate parseDate(String raw,String defaultDate){try{return LocalDate.parse(raw==null||raw.isBlank()?defaultDate:raw);}catch(Exception e){throw new ApiException(HttpStatus.BAD_REQUEST,"VALIDATION_ERROR","deliveryDate must use YYYY-MM-DD format.");}}
 private Long reserveIdempotencyKey(long userId,String key){try{jdbc.update("insert into idempotency_records(user_id,idempotency_key,order_id,request_hash,response_status) values(?,?,null,?,?)",userId,key,"in-progress",102);return null;}catch(DuplicateKeyException e){Long orderId=singleLong("select order_id from idempotency_records where user_id=? and idempotency_key=? and order_id is not null",userId,key);if(orderId!=null)return orderId;throw new ApiException(HttpStatus.CONFLICT,"IDEMPOTENCY_IN_PROGRESS","This order request is still being processed. Please retry shortly.");}}
 private String displayStatus(String status){return status.substring(0,1)+status.substring(1).toLowerCase(Locale.ROOT);} private Long singleLong(String s,Object... a){var r=jdbc.query(s,(rs,n)->rs.getLong(1),a);return r.isEmpty()?null:r.get(0);}private String dishName(long id){return jdbc.queryForObject("select name from dishes where id=?",String.class,id);}private record Calculated(long dishId,String name,long unit,int quantity,long subtotal,List<OrderOption> options){}
}
